/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { View, TouchableOpacity } from 'react-native';
import TabSwipe, { withContext, withSwipeControl, withTabControl } from 'react-native-tab-swipe'

const TabSwipeWithTabControl = withContext(withTabControl(withSwipeControl(TabSwipe)))

export default class App extends Component<{}> {
  state = {
    index: 1
  }
  render() {
    return (
      <TabSwipeWithTabControl
        onPressTab={(newIndex) => this.setState({ index: newIndex })}
        index={this.state.index}
      >
        <View style={{ width: '100%', height: 200, backgroundColor: 'yellow' }} />
        <View style={{ width: '100%', height: 200, backgroundColor: 'grey' }} />
        <View style={{ width: '100%', height: 200, backgroundColor: 'cyan' }} />
      </TabSwipeWithTabControl>
    );
  }
}
