/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component, useState, useRef, useEffect } from 'react';
import { Platform, StyleSheet, Text, View, TouchableOpacity as Touchable, Animated } from 'react-native';
import TabSwipe from 'react-native-tab-swipe';

export default class App extends Component<{}> {
  state = {
    index: 1
  }
  render() {
    return (
      <TabSwipe
        onPressTab={(newIndex) => this.setState({ index: newIndex })}
        index={this.state.index}
      />
    );
  }
}
